### ISSUE TITLE
[S1-PB1] Membuat Register

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#10]
Sebagai Pengguna, saya bisa mengakses dan melakukan registrasi atau pembuatan akun, untuk melakukan login.

-------------- Proses Bisnis --------------------

![Image](https://user-images.githubusercontent.com/115538474/227816727-cdad04c7-507c-41eb-9460-537a10621bd9.png)

---------------                     ---------------------

-------------------------------------------------
Codingan dan Tampilan web fitur registrasi
-------------------------------------------------

![Image](https://user-images.githubusercontent.com/43942051/228160469-dbed5806-6a89-4a33-9af8-69abd6d1d347.png)

![Image](https://user-images.githubusercontent.com/43942051/228160548-6920ca9f-d38c-43e1-87d1-5385177de4ab.png)

![Image](https://user-images.githubusercontent.com/43942051/228160584-8f01f9cb-6c19-48d9-8f63-d800402fa078.png)

**Comment by bayusatrio04** [comment]
Sudah selesai untuk fitur register

**Comment by TaufiqMF** [comment]
close
