### ISSUE TITLE
[S1-PB3] Membuat Landing Page

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#12]
[S1-PB3] Membuat Landing Page #12
Sebagai user, saya ingin dapat melihat Landing Page atau halaman utama, tampilan awal bagi user atau pengguna untuk mengakses semua layanan pada aplikasi adaHEALTH

![Image](https://user-images.githubusercontent.com/115538474/227816817-686f89d9-8b08-40c3-8f5d-3da103396084.png)

---------------------------------------
Halaman Landingpage atau Home dari ada HEALTH

![Image](https://user-images.githubusercontent.com/84509538/229133380-b27d55ff-87e9-4829-9bfa-1cf6de0c5c87.png)

----------------------------------------
Codingan dari Halaman Landingpage atau HOME

![Image](https://user-images.githubusercontent.com/84509538/229133479-ef3f9d55-325b-4bcf-ad2e-436675baaa6d.png)

![Image](https://user-images.githubusercontent.com/84509538/229133504-b0e9a02b-b11d-46f0-9dba-67df0ffd3a9b.png)

![Image](https://user-images.githubusercontent.com/84509538/229133525-59cf6ded-63a7-496e-9396-074085c17268.png)

![Image](https://user-images.githubusercontent.com/84509538/229133563-fad979df-74e4-4095-ade9-1c434154aedb.png)

**Comment by TaufiqMF** [comment]
close

**Comment by TaufiqMF** [comment]
close
