### ISSUE TITLE
[S1-PB5] Membuat Rekomendasi Rumah Sakit

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#15]
Sebagai user, saya ingin ada Fitur rekomendasi rumah sakit dibuat agar pengguna dapat mengetahui rumah sakit mana saja yang direkomendasikan oleh aplikasi sehingga pengguna tidak perlu memakan waktu hanya untuk mencari rumah sakit yang banyak dikunjungi oleh masyarakat.

![Image](https://user-images.githubusercontent.com/115538474/227817286-fe9b8727-1cc5-4816-a049-cbfd8c3ec48e.png)

-------------------------------------
Berikut tampilan website dari rekomendasi rumah sakit 

![Image](https://user-images.githubusercontent.com/84509538/230793191-9fd6cf5e-1e5c-479a-bdad-07951638f2fa.png)

![Image](https://user-images.githubusercontent.com/84509538/230793206-b0440cb6-3c17-48eb-9f06-deaa5ffee644.png)

![Image](https://user-images.githubusercontent.com/84509538/230793211-c9d38a6c-3b27-4813-a6fc-3ca31c3d98d4.png)

![Image](https://user-images.githubusercontent.com/84509538/230793220-bb4bff08-7aea-41af-b0b5-17f567fbe2bb.png)

Berikut codingan nya 
---------------------------------------

![Image](https://user-images.githubusercontent.com/84509538/230793234-cf7b7420-99b9-4419-9be2-fedacf6784f2.png)

![Image](https://user-images.githubusercontent.com/84509538/230793239-4440b373-c4f2-4c00-9ee9-18a472c7cf70.png)

**Comment by TaufiqMF** [comment]
close
