### ISSUE TITLE
[S1-PB9] Membuat Rekomendasi Harga Obat dan Jenis Obat

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#16]
Fitur Rekomendasi Harga Obat dan Jenis Obat dibuat agar pengguna dapat mengetahui jenis obat apa yang direkomendasikan untuk penyakit tertentu dan tentu harga serta kualitas dari obat tersebut, sehingga saya mengetahui bahwa tidak salah pilih obat.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/230813445-c577ef29-e974-4b94-ac6d-8155990fdc67.png)

Tampilan Design : 

![Image](https://user-images.githubusercontent.com/84509538/230802602-f2356ea9-ef43-4d19-aaaa-904d7014abfd.png)

Codingan untuk Fitur ini : 

![Image](https://user-images.githubusercontent.com/84509538/230762557-fb98815a-487d-427c-b0aa-85a94c0181a7.png)

![Image](https://user-images.githubusercontent.com/84509538/230762566-22a02368-751c-408e-82a4-94c0b9e07853.png)

![Image](https://user-images.githubusercontent.com/84509538/230762572-06971de8-b61a-432b-a175-1de4dd606f30.png)

**Comment by TaufiqMF** [comment]
close
