### ISSUE TITLE
[S2-PB15] Membuat Chat Dokter Spesialis

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#17]
Saya sebagai pengguna, ingin bisa konsultasi dengan dokter spesialis dimanapun dan kapanpun secara daring, sehingga saya dapat menanyakan apa yang saya alami terutama penyakit apa yang saya derita.

Fitur chat dengan dokter spesialis dibuat untuk memudahkan pengguna dapat melakukan konsultasi dengan dokter spesialis, sehingga pengguna dapat menanyakan apa yang saya alami terutama penyakit apa yang diderita secara daring.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231341041-13c28b2b-f46e-4ddd-8f75-a4ca0d9f9154.png)

Tampilan :

![Image](https://user-images.githubusercontent.com/115643228/236690640-5282a423-3e03-4cb8-8b64-101fcc0f735d.png)

**Comment by tienfkusumasari** [comment]
koneksi ke wa belum nyambung

**Comment by tienfkusumasari** [comment]
done (SP2)
