### ISSUE TITLE
[S1-PB6] Membuat Rekomendasi Apotek

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#19]
[S1-PB6] Membuat Rekomendasi Apotek #19

Fitur ini dapat memudahkan pengguna dalam mencari apotek yang menyediakan semua jenis obat, sehingga saya tidak perlu lagi mencari apotek yang tidak tersedia obatnya.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/230813660-4b38f115-8be2-4ba4-b354-2a26b60172c3.png)

Mockup:

![image](https://user-images.githubusercontent.com/115538474/230803467-eb33f7be-3dfc-47f4-95fb-596a7c337c9f.png)

![image](https://user-images.githubusercontent.com/115538474/230803576-45e17af1-a70c-48a9-b967-869f2cfc3652.png)

**Comment by TaufiqMF** [comment]
close

**Comment by TaufiqMF** [comment]
close
