### ISSUE TITLE
[S2-PB8] Membuat Pelacak Kesehatan

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#22]
Saya sebagai pengguna, ingin mengetahui kesehatan saya. Dengan adanya fitur pelacakan kesehatan saya dapat mengetahui kondisi tubuh saya dimana saya akan mendapat informasi, laporan kesehatan atau diagnosis umum mengenai kondisi tubuh berdasarkan informasi atau data yang nantinya saya inputkan.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231339023-67e3998f-e4bd-4f18-aff4-2701e25305f1.png)

Mockup:

![Image](https://user-images.githubusercontent.com/84509538/231339311-666c1120-5e3c-42a1-bc52-cd50f470f4a6.png)

![Image](https://user-images.githubusercontent.com/84509538/231339318-ca998712-8d25-4bcf-b87b-e1b61b307152.png)

![Image](https://user-images.githubusercontent.com/84509538/231339344-900acf93-f543-4849-9898-b794ea777aa9.png)

![Image](https://user-images.githubusercontent.com/84509538/231339357-940ebd1a-df69-4216-9a54-691ba699aa7f.png)

**Comment by tienfkusumasari** [comment]
belum demo

**Comment by tienfkusumasari** [comment]
done dengan catatan : tambahkan tree kepututsan di issue dan lakukan tunning

**Comment by tienfkusumasari** [comment]
done dengan catatan issue dilengkapi dengan tree dan
