### ISSUE TITLE
[S1-PB7] Membuat Help Whatsapp/Website

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#24]
Saya sebagai pengguna, ingin adanya bantuan yang mengarahkan ke whatsapp atau langsung dari website, sehingga saya dapat menanyakan perihal ketidaktahuan pada aplikasi maupun tata cara pencarian layanan kesehatan di aplikasi “adaHEALTH”.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/230813551-d81dca98-c72a-4bac-9803-b661b7327ee4.png)

**Comment by jizdanr** [comment]
![Image](https://user-images.githubusercontent.com/115643228/229369002-c1ecc606-ae02-4570-a70c-6c88b141c09d.png)

**Comment by jizdanr** [comment]
![Image](https://user-images.githubusercontent.com/115643228/229369082-67a3171e-a386-416d-ab8a-818a6d4295d0.png)



![Image](https://user-images.githubusercontent.com/115643228/229369100-37e349fc-b117-480f-b283-38764477c5cd.png)



![Image](https://user-images.githubusercontent.com/115643228/229369114-c7ef63b6-6da2-400b-bc73-931a7eb02239.png)

**Comment by TaufiqMF** [comment]
close
