### ISSUE TITLE
[S2-PB4] Membuat Feedback User Aplikasi

### ISSUE THREAD

**Issue by auliaucheni** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#29]
Saya sebagai pengguna, ingin adanya penilaian terhadap aplikasi, sehingga untuk kedepannya aplikasi “adaHEALTH” bisa menerima kritikan maupun saran untuk perkembangan lebih lanjut.

- User dapat membuat dan melihat history feedback yang telah dibuat.
- Admin dapat melihat keseluruhan feedback yang dibuat oleh semua user.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231338691-25217ee9-8cb3-4122-bf97-f651e90837d1.png)

Mockup:

![Image](https://user-images.githubusercontent.com/84509538/231337778-451f1b21-0620-41e2-9833-525f03f4f988.png)

**Comment by tienfkusumasari** [comment]
done (SP2)
