### ISSUE TITLE
[S2-PB14] Membuat History Transaksi

### ISSUE THREAD

**Issue by auliaucheni** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#33]
Saya sebagai pengguna, ingin mengetahui transaksi apa saja yang sudah saya lakukan.
Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231340452-7e521a9d-dffc-41ff-8ba3-441fb7071f1e.png)

Mockup:

![Image](https://user-images.githubusercontent.com/115632549/236709087-f03e78b4-2d7a-468a-8e11-edfb72d0d3a6.jpg)

**Comment by tienfkusumasari** [comment]
done (SP2)
