### ISSUE TITLE
[S2-PB10] Membuat Kalkulator BMI

### ISSUE THREAD

**Issue by auliaucheni** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#35]
Saya sebagai pengguna, ingin mengetahui berat badan saya apakah ideal atau tidak, sehingga saya dapat melakukan konsultasi dengan dokter spesialis jika tidak termasuk kategori yang bukan ideal.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231341684-fe9e368e-a34f-4609-b3cf-4f7511fbded9.png)

Mockup:

![Image](https://user-images.githubusercontent.com/84509538/231341436-767fd1f4-e97e-458c-a76e-714c45d345af.png)

![Image](https://user-images.githubusercontent.com/84509538/231341550-d62bddc8-f183-4dcb-a5b0-0aa35eaf6a08.png)

![Image](https://user-images.githubusercontent.com/84509538/231341602-552bd9c2-aea8-45ed-adec-22269366eac3.png)

Rumus BMI:
BMI = Berat Badan (kg) / (Tinggi Badan)² (meter)

Keterangan klasifikasi ideal, obesitas, dll: (under,normal,..)

![Image](https://user-images.githubusercontent.com/113256097/236833197-68e256bf-4001-458e-973f-89eaa01bf784.png)

**Comment by tienfkusumasari** [comment]
detail issue perlu di tambahkan, code done

**Comment by tienfkusumasari** [comment]
done SP2
