### ISSUE TITLE
[S1-PB8] Migrate Database

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#47]
saya membutuhkan untuk migrations database. untuk bisa memproses atau mengintegrasi dari beberapa fitur yang terdapat di project adaHEALTH.

![Image](https://user-images.githubusercontent.com/43942051/228156843-4dfa0a82-51f0-4d13-a434-393c991a6315.png)

Migrate Struktur database
----------------------------------

![Image](https://user-images.githubusercontent.com/43942051/230803781-b551ad11-3d06-4616-a363-55c929de5328.png)

![Image](https://user-images.githubusercontent.com/43942051/230803788-2416caad-8400-4fc2-a35f-015e7c9941b7.png)

![Image](https://user-images.githubusercontent.com/43942051/230803795-c91beaa3-9b35-47e9-b622-14f39b726cff.png)

![Image](https://user-images.githubusercontent.com/43942051/230803810-5498dca9-3d0f-4af0-a14d-918405faf8cd.png)

![Image](https://user-images.githubusercontent.com/43942051/230803820-d18ddfe8-4e94-421f-9835-dcf84385b679.png)

![Image](https://user-images.githubusercontent.com/43942051/230803835-3d41de9e-0463-4878-811b-161c165275ef.png)

![Image](https://user-images.githubusercontent.com/43942051/230803745-f841f309-29c6-4b0f-bd2b-a92bdd07a9e2.png)

**Comment by TaufiqMF** [comment]
close
