### ISSUE TITLE
[S2-PB22] Membuat CRUD Apotek

### ISSUE THREAD

**Issue by bayusatrio04** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#52]
User Stories :

Saya sebagai admin, ingin menambahkan atau membuat fitur rekomendasi Apotek, melihat Apotek, mengubah Apotek dan menghapus Apotek . supaya user dapat melihat Apotekmana yang direkomendasikan sistem.
Probis : 

![Image](https://user-images.githubusercontent.com/43942051/236672693-4f6a9a87-e64c-4251-a9a3-3cb67dc88a79.png)

Mockup : 

![Image](https://user-images.githubusercontent.com/43942051/236175516-8368bbcc-39d3-44ae-91c7-bc724f10e2a1.png)

![Image](https://user-images.githubusercontent.com/43942051/236175528-7af22540-6526-4ed3-8cdb-c4a1122e5b7c.png)

![Image](https://user-images.githubusercontent.com/43942051/236175536-8fee8a26-f4fd-4c5c-8f46-9ea069d2b59a.png)

-----------------------------------------
User Interface Website : 
-----------------------------------------

![Image](https://user-images.githubusercontent.com/43942051/236176053-49ce7fc0-4704-493b-be7c-870b27d76b37.png)

![Image](https://user-images.githubusercontent.com/43942051/236176107-76c6b958-70fb-440f-8449-01df62f95f6e.png)

![Image](https://user-images.githubusercontent.com/43942051/236176148-06b19524-9d7d-4759-b967-4f62564f74a7.png)

**Comment by tienfkusumasari** [comment]
gambar belum muncul (SP2)

**Comment by tienfkusumasari** [comment]
done (SP2)
