### ISSUE TITLE
[S2-PB24] CRUD Dokter Spesialis

### ISSUE THREAD

**Issue by jizdanr** [SI-RPL-2023/SI4401_KEL224_adaHEALTH#54]
Saya sebagai admin, ingin membuat user bisa konsultasi dengan memilih dokter spesialis yang saya butuhkan dimanapun dan kapanpun secara daring, sehingga saya dapat membantu user menanyakan apa yang mereka alami terutama penyakit apa yang mereka derita.

Proses Bisnis:

![Image](https://user-images.githubusercontent.com/84509538/231341041-13c28b2b-f46e-4ddd-8f75-a4ca0d9f9154.png)

Tampilan : 

add dokter 

![Image](https://user-images.githubusercontent.com/115643228/236690219-7b9167b4-0b12-41cb-a313-37236aa6123f.png)

![Image](https://user-images.githubusercontent.com/115643228/236690187-8eb5c4f8-5b9b-4882-8ca1-0bc7db8d663e.png)

Edit

![Image](https://user-images.githubusercontent.com/115643228/236690332-e84d7f59-d2b8-46ce-b55a-6d438784c4cb.png)

Delete 

![Image](https://user-images.githubusercontent.com/115643228/236690455-aeff3bad-b7b6-460d-892d-575fd85f340b.png)

**Comment by tienfkusumasari** [comment]
done , cek case cade delete (SP2)
